# PCA
http://zellij.hatenablog.com/entry/20130510/p1  
http://heycere.com/statistics/covariance/
  
ラグランジュの未定乗数法？

In [1]:
import numpy as np
import pandas as pd

In [3]:
matrix = [
    [93, 100, 89, 168, 154],
    [100, 98, 89, 190, 172],
    [84, 84, 99, 170, 200],
    [70, 73, 92, 132, 154],
    [70, 72, 89, 132, 150],
    [66, 68, 95, 114, 164],
    [74, 70, 96, 186, 176],
    [74, 75, 95, 140, 158],
    [76, 77, 92, 156, 163],
    [79, 88, 100, 172, 200]
]
df = pd.DataFrame(
    matrix,
    index=['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J'],
    columns=['国語', '社会', '理科', '英語', '数学']
)

In [4]:
print("国語 / 社会 / 理科 : 100点満点")
print("英語 / 数学 : 200点満点")
df

国語 / 社会 / 理科 : 100点満点
英語 / 数学 : 200点満点


国語   社会   理科   英語   数学
A   93  100   89  168  154
B  100   98   89  190  172
C   84   84   99  170  200
D   70   73   92  132  154
E   70   72   89  132  150
F   66   68   95  114  164
G   74   70   96  186  176
H   74   75   95  140  158
I   76   77   92  156  163
J   79   88  100  172  200

## 分散共分散行列（共分散行列）

https://omedstu.jimdo.com/2018/03/28/%E5%88%86%E6%95%A3%E5%85%B1%E5%88%86%E6%95%A3%E8%A1%8C%E5%88%97%E3%82%92%E7%9B%B8%E9%96%A2%E8%A1%8C%E5%88%97-%E5%81%8F%E7%9B%B8%E9%96%A2%E4%BF%82%E6%95%B0%E3%81%AB%E5%A4%89%E6%8F%9B-python/

In [56]:
cov=df.cov()

In [57]:
cov

国語          社会         理科          英語          数学
国語  116.711111  117.222222 -12.288889  206.666667   46.377778
社会  117.222222  132.500000 -10.777778  186.666667   49.500000
理科  -12.288889  -10.777778  16.488889   11.777778   59.600000
英語  206.666667  186.666667  11.777778  647.111111  251.555556
数学   46.377778   49.500000  59.600000  251.555556  330.322222

In [71]:
# 対角成分抽出
np.diag(cov)

array([116.71111111, 132.5       ,  16.48888889, 647.11111111,
       330.32222222])

In [72]:
# 各対角成分を -1/2乗
np.power(np.diag(cov),-0.5)

array([0.09256438, 0.08687445, 0.24626591, 0.03931068, 0.05502133])

In [76]:
# 対角行列を作成
D=np.diag(np.power(np.diag(cov),-0.5))
D

array([[0.09256438, 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.08687445, 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.24626591, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.03931068, 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.05502133]])

In [75]:
np.dot(D,cov)

array([[10.80329168, 10.85060236, -1.13751339, 19.12997194,  4.29293026],
       [10.18361591, 11.51086443, -0.9363135 , 16.21656373,  4.3002852 ],
       [-3.02633445, -2.65419929,  4.06065129,  2.90046521, 14.67744846],
       [ 8.12420748,  7.33799386,  0.46299247, 25.4383787 ,  9.88882029],
       [ 2.55176713,  2.72355596,  3.27927142, 13.84092188, 18.17476884]])

In [77]:
np.dot(np.dot(D,cov),D)

array([[ 1.        ,  0.9426401 , -0.28013077,  0.75201223,  0.23620274],
       [ 0.9426401 ,  1.        , -0.2305821 ,  0.63748417,  0.23660742],
       [-0.28013077, -0.2305821 ,  1.        ,  0.11401926,  0.80757277],
       [ 0.75201223,  0.63748417,  0.11401926,  1.        ,  0.54409607],
       [ 0.23620274,  0.23660742,  0.80757277,  0.54409607,  1.        ]])

## 標準化

In [52]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()


In [53]:
df_std = pd.DataFrame(
    sc.fit_transform(df),
    index=['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J'],
    columns=['国語', '社会', '理科', '英語', '数学']
)

In [54]:
df_std

国語        社会        理科        英語        数学
A  1.405029  1.785687 -1.194101  0.497245 -0.875763
B  2.088028  1.602540 -1.194101  1.408861  0.168193
C  0.526886  0.320508  1.401770  0.580119  1.792125
D -0.839114 -0.686803 -0.415339 -0.994490 -0.875763
E -0.839114 -0.778377 -1.194101 -0.994490 -1.107754
F -1.229400 -1.144671  0.363422 -1.740358 -0.295788
G -0.448829 -0.961524  0.623009  1.243113  0.400183
H -0.448829 -0.503655  0.363422 -0.662994 -0.643773
I -0.253686 -0.320508 -0.415339  0.000000 -0.353785
J  0.039029  0.686803  1.661357  0.662994  1.792125

## 相関行列

In [48]:
# NumPyのcorrcoefはデフォルトでは行間の相関係数を計算
# pandasのデータフレームのcorr()メソッドは、列間の相関を計算

correlation_matrix=df_std.corr()
correlation_matrix

国語        社会        理科        英語        数学
国語  1.000000  0.942640 -0.280131  0.752012  0.236203
社会  0.942640  1.000000 -0.230582  0.637484  0.236607
理科 -0.280131 -0.230582  1.000000  0.114019  0.807573
英語  0.752012  0.637484  0.114019  1.000000  0.544096
数学  0.236203  0.236607  0.807573  0.544096  1.000000

## 固有値、固有ベクトル

In [103]:
w,v=np.linalg.eig(correlation_matrix)

In [104]:
# 固有値は、説明変数の数と一致
# 値が大きい順に第１主成分、第２主成分、・・・、第５主成分
w

array([2.75351334, 1.85890988, 0.29707803, 0.02963954, 0.0608592 ])

In [105]:
# 固有ベクトルは、説明変数の数と一致
# 固有ベクトル内の要素数も説明変数の数と一致
v

array([[ 0.55992543,  0.24599271,  0.13545814, -0.76330003,  0.15809885],
       [ 0.53756194,  0.23171743,  0.55348613,  0.50210283, -0.31445196],
       [ 0.02537413, -0.71904976,  0.21112241, -0.29800409, -0.59071523],
       [ 0.53860062, -0.08865464, -0.78316789,  0.17809881, -0.23870189],
       [ 0.32676627, -0.60075154,  0.13183163,  0.21151875,  0.6857125 ]])

## 寄与率

In [97]:
# 固有値の合計は、説明変数の数と一致★
w.sum()

4.999999999999994

In [121]:
# sorted()：元のリストはそのままで、並び替えられたリストを返す
w_sort=sorted(w, reverse=True)
w_sort

[2.7535133424096805,
 1.8589098815714786,
 0.29707802661740446,
 0.0608592049124812,
 0.029639544488949503]

In [122]:
# 各主成分の寄与率：（固有値 / 固有値の数）*100→つまり１説明変数あたりの固有値の値は1
for i in range(5):
    print("第"+str(i+1)+"主成分：",w_sort[i]/len(w)*100)

第1主成分： 55.070266848193604
第2主成分： 37.17819763142957
第3主成分： 5.941560532348089
第4主成分： 1.217184098249624
第5主成分： 0.5927908897789901
